### PR TITLE
Feat/testcontainers

### LINKED ISSUE #22: add test for uploading file
try using minio testcontainers https://testcontainers.com/modules/minio/ to spin up a minio container to test with

ktor test example
https://ktor.io/docs/testing.html#test-post-put

the docker-compose file here https://github.com/Open-MBEE/flexo-mms-deployment/tree/develop/docker-compose has an example of the parameters to configure for minio and store service

the api to test is https://github.com/Open-MBEE/flexo-mms-store-service/blob/develop/src/main/kotlin/org/openmbee/flexo/mms/plugins/Storage.kt#L39

### PR DESCRIPTION
**Pull request by karicordes**
Created a test for /store/{filename} route using a Minio container. Tests that the url returned by s3 services is not null and contains the name of the file passed to it.

Fixes #22

### CODE REVIEW

**Comment by blake-regalia** [comment]
@karicordes Thanks for the PR. A few issues:
1. Why is the code duplicated between ApplicationTest and StoreTest?
2. The tests are failing for me. Have you successfully run these on your local IDE? Let's touch base if you need help setting up your environment.
3. In `testEnv()`, I notice its attempting to read `"application.conf"`, which will not exist in bare repo. For this reason, we usually provide a test conf file `"application.conf.test"` filled with the test config properties like we do here: https://github.com/Open-MBEE/flexo-mms-layer1-service/tree/develop/src/main/resources

**Review by blake-regalia — CHANGES_REQUESTED** [review]
See comment

**Comment by karicordes** [comment]
Hi @blake-regalia, 

1. To my understanding the code needs the minio container running to start the store service (needs url from container to do s3 configuration during setup I think), so both ApplicationTest and StoreTest need to start the container.
2. Hmmm - the tests do pass for me, both StoreTest and ApplicationTest. I think I set my environment up correctly, but let's double check to make sure.
3. I have added the application.conf.test file (and changed StoreTest to use the new file) and retested and both tests pass for me.

**Comment by dlamoris** [comment]
replaced by #26

**Pull request closed without merging**
